-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Addi-Data GmbH 0x0004 0x00000001",
  mode = "800x480@60.73",
  position = "4480x171",
  scale = 1,
  transform = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Electric Company LS24A600U H4ZRB00990",
  mode = "2560x1440@75.00",
  position = "1920x280",
  scale = 1,
  bitdepth = 10,
  cm = "hdredid",
  sdrbrightness = 1.4,
  sdrsaturation = 0.9,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
  supports_hdr = 1,
})

hl.monitor({
  output = "desc:Sony SONY TV 0x01010101",
  mode = "1920x1080@59.02",
  position = "0x480",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Vestel Elektronik Sanayi ve Ticaret A. S. 19W_LCD_TV 0x01010101",
  mode = "1920x1080@60.00",
  position = "5280x280",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
