[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.term]
command = "foot --app-id term"
class = "term"
size = "85% 30%"
animation = "fromTop" 
lazy = "true"

[scratchpads.audio]
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
animation= "fromRight"
size = "75% 60%" 
lazy = "true"

[scratchpads.recording]
command = "obs"
class = "com.obsproject.Studio"
animation = "fromTop"
size = "60% 40%"
lazy = "true"

[scratchpads.mymusic]
command = "foot --app-id ncmpcpp rmpc"
class = "ncmpcpp"
size = "70% 30%"
animation = "fromBottom"
lazy = "true"

[scratchpads.cava]
command = "foot --app-id cava cava"
class = "cava"
size = "70% 30%"
animation = "fromTop"
lazy = "true"

[scratchpads.spot]
command = "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"
class = "Spotify"
size = "75% 40%"
animation = "fromTop"
lazy = "true"
process_tracking = "false"

[scratchpads.monitor]
command = "foot --app-id monitor btop"
class = "monitor"
animation = "fromLeft"
size = "50% 80%"
lazy = "true"

[scratchpads.clock]
command = "foot --app-id clock clock-rs"
class = "clock"
size = "50% 30%"
animation = "fromTop"
lazy = "true"

[scratchpads.calc]
command = "gnome-calculator"
class = "calc"
size = "30% 50%"
animation = "fromBottom"
lazy = "true"

[scratchpads.clipse]
command = "foot --app-id clipse clipse"
class = "clipse"
size = "30% 40%"
animation = "fromBottom"
lazy = "true"
