[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.term]
command = "ghostty --class=com.term.term"
class = "com.term.term"
size = "55% 170px"
position = "575px 635px"
animation = "fromLeft" 
lazy = "true"

[scratchpads.audio]
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
animation= "fromRight"
size = "75% 60%" 
lazy = "true"

[scratchpads.recording]
command = "obs"
class = "com.obsproject.Studio"
animation = "fromTop"
size = "60% 40%"
lazy = "true"

#[scratchpads.mymusic]
#command = "foot --app-id ncmpcpp rmpc"
#class = "ncmpcpp"
#size = "55% 40%"
#animation = "fromBottom"
#lazy = "true"

[scratchpads.spot]
command = "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"
class = "Spotify"
size = "55% 40%"
animation = "fromTop"
lazy = "true"
process_tracking = "false"

[scratchpads.monitor]
command = "foot --app-id monitor btop"
class = "monitor"
animation = "fromBottom"
size = "55% 42%"
position = "574px 826px"
lazy = "true"

[scratchpads.clock]
command = "foot --app-id clock clock-rs"
class = "clock"
size = "539px 213px"
position = "30px 60px"
animation = "fromLeft"
lazy = "true"

[scratchpads.calc]
command = "gnome-calculator"
class = "calc"
size = "542px 778px"
position = "1990px 640px"
animation = "fromBottom"
lazy = "true"

[scratchpads.clipse]
command = "foot --app-id clipse clipse"
class = "clipse"
position = "1990px 60px"
size = "548px 574px"
animation = "fromRight"
lazy = "true"

[scratchpads.weather]
command = "ghostty --class=com.we.weather --font-size=5 --command='wttr Birmingham && sleep 60'"
class = "com.we.weather"
position = "30px 273px"
size = "539px 419px"
animation = "fromLeft"
lazy = "true"

