-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = false,
        },
        inactive_opacity = 0.95,
        rounding = 0,
        shadow = {
            enabled = false,
        },
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(241f31ff)", "rgba(77767bff)"},
                angle = 45,
            },
        },
        gaps_in = 3,
        gaps_out = 6,
    },
})

-- Monitors
hl.monitor({
    output = "DP-2",
    mode = "800x480@60.73Hz",
    position = "4480x280",
    scale = 0.67,
    transform = 2,
    cm = "srgb",
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@59.02Hz",
    position = "-10x270",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.00Hz",
    position = "5680x280",
    scale = 1,
    cm = "srgb",
})
