-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Qogir")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = false,
        },
        inactive_opacity = 0.95,
        rounding = 0,
        shadow = {
            enabled = false,
        },
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(241f31ff)", "rgba(77767bff)"},
                angle = 45,
            },
        },
        gaps_in = 3,
        gaps_out = 6,
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@75.00Hz",
    position = "1890x240",
    scale = 1,
    bitdepth = 10,
    cm = "wide",
    sdrbrightness = 0.19,
    sdrsaturation = 1.38,
    sdr_min_luminance = 0,
    sdr_max_luminance = 643,
    min_luminance = 0,
    max_luminance = 800,
    max_avg_luminance = 500,
})
hl.monitor({
    output = "DP-2",
    mode = "800x480@60.73Hz",
    position = "4450x240",
    scale = 0.67,
    transform = 2,
    cm = "srgb",
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@59.02Hz",
    position = "-30x240",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.00Hz",
    position = "5650x230",
    scale = 1,
    cm = "srgb",
})
