[general]
font-sans = "Bitstream Vera Serif"

[bar]
scale = 1.149999976158142
bg = "transparent"
rounding = "full"

[[bar.layout]]
monitor = "DP-1"
show = true
left = [
    "clock",
    "systray",
    "weather",
    "separator",
]
center = [
    "separator",
    "media",
    "cava",
    "separator",
]
right = [
    "separator",
    "hyprland-workspaces",
    "microphone",
    "volume",
    "notifications",
]

[[bar.layout]]
monitor = "HDMI-A-1"
show = true
left = [
    "cpu",
    "ram",
]
center = ["systray"]
right = [
    "window-title",
    "hyprland-workspaces",
]

[styling]
theme-provider = "pywal"

[modules.cava]
color = "#531313"
bar-width = 10
left-click = "/home/tagilla/.Scripts/PyprMenu.zsh"
right-click = "fuzzel"

[modules.clock]
format = "%a %b %d %H:%M:%S"
icon-bg-color = "#531313"
label-color = "#531313"

[modules.hyprland-workspaces]
min-workspace-count = 1
monitor-specific = false
show-special = false
display-mode = "icon"
app-icons-show = true

[modules.media]
icon-type = "spinning-disc"
icon-bg-color = "#531313"
label-color = "#531313"
right-click = "pypr toggle mymusic"
middle-click = "pypr toggle spot"
scroll-up = "rmpc volume +5"
scroll-down = "rmpc volume -5"

[modules.microphone]
icon-bg-color = "#531313"
label-color = "#531313"

[modules.network]
icon-bg-color = "#531313"
label-color = "#531313"

[modules.volume]
icon-bg-color = "#531313"
label-color = "#531313"
scroll-up = "wayle audio output-volume +5"
scroll-down = "wayle audio output-volume -5"

[modules.weather]
location = "Birmingham"
weatherapi-key = "09eab95b9039458a9c0115139261606"
icon-bg-color = "#531313"
label-color = "#531313"

[wallpaper]
engine-enabled = false
