#[[]]
#on = [ "" ]
#run = ""


[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on  = "<C-n>"
run = "shell -- dragon-drop -x -i -T %h"

[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = "plugin kdeconnect-send"
desc = "Send selected files via KDE Connect"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "shell -- lp %h"
desc = "print highlighted file"

[[mgr.prepend_keymap]]
on = [ "g", "T" ]
run = "cd ~/.local/share/Trash"
desc = "Travel to trash"

[[mgr.prepend_keymap]]
on = [ "R", "b" ]
run = "plugin recycle-bin"
desc = "Open recycle bin"

[[mgr.prepend_keymap]]
on = [ "g", "E" ]
run = "cd /mnt/baefb291-842c-4d6a-9fed-7bca7e63deeb"
desc = "Travel to XtraSSD"

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on = [ "g", "b" ]
run = "cd /home/tagilla/TemporaryNasStuff/Batchdump"
desc = "Travel to Batchdump"

[[mgr.prepend_keymap]]
on = [ "g", "v" ]
run = "cd /home/tagilla/Videos"
desc = "Travel to Videos"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "cd /home/tagilla/Pictures"
desc = "Travel to Pictures" 

[[mgr.prepend_keymap]]
on = [ "g", "D" ]
run = "cd /home/tagilla/Documents"
desc = "Travel to Documents" 

[[mgr.prepend_keymap]]
on = [ "g", "m" ]
run = "cd /home/tagilla/Music"
desc = "Travel to Music"

[[mgr.prepend_keymap]]
on = [ "g", "G" ]
run = "cd /home/tagilla/.local/share/Steam/steamapps/common"
desc = "Travel to Steam games folder"

[[mgr.prepend_keymap]]
on = [ "e", "m" ]
run = "plugin chmod"
desc = "Chmod files"

[[mgr.prepend_keymap]]
on = [ "e", "g" ]
run = "shell --block 'gradia %h' "
desc = "Edit with Gradia"

[[mgr.prepend_keymap]]
on = [ "e", "n" ]
run = "shell --block 'nvim %h' "
desc = "Edit with nvim"

[[mgr.prepend_keymap]]
on = "<C-g>"
run = "plugin open-git-remote"
desc = "Open github page"

[[mgr.prepend_keymap]]
on = "<C-l>"
run = "plugin lazygit"
desc = "Initiate Lazygit"

[[mgr.prepend_keymap]]
on = [ "g", "C" ]
run = "cd /home/tagilla/dotfiles"
desc = "Travel to Dotfiles" 

[[mgr.prepend_keymap]]
on = [ "e", "f" ]
run = "shell --block 'go run github.com/dgr8akki/nano-ffmpeg@latest -d %h' "
desc = "Initiate ffmpeg"

