-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Qogir")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = false,
        },
        inactive_opacity = 0.95,
        rounding = 13,
        shadow = {
            enabled = false,
        },
    },
    dwindle = {
        smart_split = false,
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(241f31ff)", "rgba(77767bff)"},
                angle = 45,
            },
        },
        gaps_in = 3,
        gaps_out = 6,
    },
    input = {
        numlock_by_default = true,
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@75.00Hz",
    position = "690x240",
    scale = 1,
    bitdepth = 10,
    cm = "adobe",
    sdrbrightness = 0.19,
    sdrsaturation = 1.38,
    sdr_min_luminance = 0,
    sdr_max_luminance = 643,
    min_luminance = 0,
    max_luminance = 800,
    max_avg_luminance = 500,
})
hl.monitor({
    output = "DP-2",
    mode = "800x480@60.73Hz",
    position = "-270x480",
    scale = 0.83,
    transform = 2,
    cm = "srgb",
})
hl.monitor({
    output = "DP-3",
    mode = "800x480@60.73Hz",
    position = "3250x270",
    scale = 0.83,
    transform = 2,
    cm = "srgb",
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.00Hz",
    position = "4210x260",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("asryx"))
hl.unbind("XF86Tools")
hl.bind("XF86Tools", hl.dsp.exec_cmd("pypr toggle mymusic spot"))
hl.unbind("SUPER + SHIFT + Return")
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("ghostty -e nvim"))
hl.unbind("SUPER + CTRL + B")
hl.bind("SUPER + CTRL + B", hl.dsp.exec_cmd("fuzzel"))
hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.exec_cmd("obsidian"))

-- Window rules
hl.window_rule({
    match = {
        class = "^(waypaper)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(destiny_linux_amd64\\.AppImage)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(walls)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(walls)$",
    },
    move = "700 250",
})
hl.window_rule({
    match = {
        class = "^(com\\.gabm\\.satty)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(satty)$",
    },
    move = "= {\"cursor_x-(window_w*0.5)\", \"cursor_y-(window_h*0.5)\"}",
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("foot -e calcure")
    hl.exec_cmd("gsr-ui")
    hl.exec_cmd("env LD_PRELOAD=/usr/lib32/libextest.so steam")
end)
