# ── Font ─────────────────────────────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0

# Ligatures
disable_ligatures            never

# ── Transparency (Hyprland handles blur via windowrules) ──────────────────────
# background_opacity         1
# dynamic_background_opacity yes

# URL underline
# url_color                #F5C2E7
url_style                  curly

# ── Tab Bar ───────────────────────────────────────────────────────────────────
tab_bar_edge               bottom
tab_bar_style              powerline
tab_powerline_style        slanted
tab_bar_min_tabs           1
tab_title_template         " {index}: {title} "
# active_tab_foreground    #1E1E2E
# active_tab_background    #CBA6F7
active_tab_font_style      bold
# inactive_tab_foreground  #CDD6F4
# inactive_tab_background  #313244
inactive_tab_font_style    normal
# tab_bar_background       #181825

# ── Window ────────────────────────────────────────────────────────────────────
window_padding_width       8
hide_window_decorations    yes
remember_window_size       yes

# Window border colours
# active_border_color      #CBA6F7
# inactive_border_color    #313244

# ── Bell ──────────────────────────────────────────────────────────────────────
enable_audio_bell          no
visual_bell_duration       0.0

# ── Performance ───────────────────────────────────────────────────────────────
repaint_delay              8
input_delay                2
sync_to_monitor            yes

# ── Misc ──────────────────────────────────────────────────────────────────────
scrollback_lines           10000
copy_on_select             yes
strip_trailing_spaces      smart
cursor_blink_interval      0.5
cursor_shape               underline
cursor_underline_thickness 2.0
cursor_trail               2
cursor_trail_decay         0.1 0.4
cursor_beam_thickness      1.5
# cursor_trail_color         #dbd800 


# BEGIN_KITTY_THEME
# E-Ink Dark
include current-theme.conf
# END_KITTY_THEME

# ── Cursor ─────────────────────────────────────────────
shell_integration        no-cursor
# cursor                   #dbd800
# cursor_text_color        #dbd800
